datasource:
  default: ${APP_ENV}

  development:
  db:
    username: ""
    password: ""
    url: jdbc:h2:mem:app
  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}

ebean:
  development:
    migration:
      run: true
  production:
    migration:
      run: true
