datasource:
  default: ${APP_ENV}
  development:
    username: sobad
    password: 123
    url: jdbc:h2:./project_database
  production:
    username: ${PGUSER}
    password: ${PGPASSWORD}
    url: jdbc:${DATABASE_URL}

ebean:
  migration:
    run: true
